### ISSUE TITLE
Some problems: curl: (7) Couldn't connect to server

### ISSUE THREAD

**Issue by craudilho1199** [code-developers/sms-spoof#1]
Hi bro!
I need help.
A screenshot of the error from the terminal is attached
![last_spoof_sms_help_net_connecta_k_serveru](https://user-images.githubusercontent.com/84741432/119550316-efc4c800-bda0-11eb-8a1f-ac2c54916c54.PNG)

Maybe i need to set up Proxy Chains or Curl somehow? 
If i need to make changes, please tell me how )
Btw Could there be a problem that I use VPN with the Tor tunnel too?

**Comment by craudilho1199** [comment]
Hello friend
I still need your help )

**Comment by krishpranav** [comment]
sorry for late reply brother

**Comment by krishpranav** [comment]
you have the latest version on proxychains if you dont have means
```
sudo apt-get install proxychains4
```
